### nn中的Conv2d，神经网络中的卷积操作

导包

In [6]:
import torch
import torch.nn.functional as F

In [3]:
# 输入矩阵
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]])
# 卷积核
kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])
print(input.shape)
print(kernel.shape)

torch.Size([5, 5])
torch.Size([3, 3])


对于torch.nn.functional.conv2d的参数有一些要求：

input – input tensor of shape $(\text{minibatch} , \text{in\_channels} , iH , iW)$


weight – filters of shape $(\text{out\_channels} , \frac{\text{in\_channels}}{\text{groups}} , kH , kW)$


bias – optional bias tensor of shape $(\text{out\_channels})$. Default: None


stride – the stride of the convolving kernel. Can be a single number or a tuple $(sH, sW)$. Default: 1


进行满足格式的tensor变形

In [4]:
input = torch.reshape(input, (1,1,5,5))
kernel = torch.reshape(kernel, (1,1,3,3))
print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [7]:
output = F.conv2d(input=input, weight=kernel, stride=1)
print(output)

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [8]:
output2 = F.conv2d(input=input, weight=kernel, stride=2)
print(output2)

tensor([[[[10, 12],
          [13,  3]]]])


In [9]:
output3 = F.conv2d(input=input, weight=kernel, stride=1, padding=1)
print(output3)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
